import type { VendorJoinPageContent } from "@workspace/db";

export const defaultVendorJoinPageContent: VendorJoinPageContent = {
  hero: {
    callLabel: "Rare District / Vendor Call",
    eyebrow: "For the labels with receipts",
    intakeLabel: "2026 intake open",
    titleLine1: "Join the",
    titleLine2: "Vanguard.",
    description: "You make the pieces people ask about in the group chat. Put your work in front of a district that knows the difference.",
    tags: ["Lagos → London → everywhere", "Curated, not crowded", "Your label. Your pace."],
  },
  brief: {
    kicker: "01 / The brief",
    headline: "Show the work,\nnot the pitch deck.",
    lookingForLabel: "What we’re looking for",
    lookingFor: ["A clear point of view", "Pieces that hold up offline", "A brand ready for its next room"],
    note: "No bank or payout details here. If your application is approved, those are handled privately in onboarding.",
  },
  form: {
    eyebrow: "Vendor application",
    title: "Drop your signal.",
    progressLabel: "04",
    contactLegend: "Contact",
    contactAccent: "/ who’s behind it",
    fullNameLabel: "Full name",
    fullNamePlaceholder: "Your name",
    emailLabel: "Email",
    emailFallback: "Your Rare District account",
    phoneLabel: "Phone / WhatsApp",
    phonePlaceholder: "+234 / +44 / ...",
    brandLegend: "Brand file",
    brandAccent: "/ the context",
    brandNameLabel: "Brand name",
    brandNamePlaceholder: "The label on the tag",
    categoryLabel: "Primary category",
    categoryPlaceholder: "Choose your lane",
    experienceLabel: "How long have you been operating?",
    experiencePlaceholder: "Pick one",
    bioLabel: "Short brand bio",
    bioPlaceholder: "What do you make? What makes it yours? Give us the short version.",
    bioHint: "Minimum 20 characters. Be specific.",
    proofLegend: "Proof of work",
    proofAccent: "/ make it visual",
    socialLabel: "Instagram handle, portfolio, or website",
    socialPlaceholder: "@yourlabel or https://yourlabel.com",
    socialHint: "Required. This is how the curation team meets the work.",
    samplesLabel: "3–5 product samples",
    uploadTitle: "Drop images here or tap to upload",
    uploadHint: "3–5 JPG, PNG or WEBP files · 1.5 MB each",
    uploadingLabel: "Uploading…",
    uploadedSuffix: "uploaded",
    rules: {
      bioMinLength: 20,
      minSamples: 3,
      maxSamples: 5,
      maxImageBytes: 1_500_000,
    },
    submitLabel: "Submit for curation",
    submittingLabel: "Sending signal…",
    legal: "By submitting, you confirm the samples are your work and agree to a curated review. No financial information is collected at this stage.",
  },
  status: {
    pendingLabel: "In review",
    pendingTitle: "Your signal is in.",
    pendingDescription: "We’re reviewing {{brandName}} now. Expect a real answer, not a black hole.",
    rejectedLabel: "Application closed",
    rejectedTitle: "Not this drop.",
    rejectedDescription: "The current edit wasn’t the right fit. Keep building—new calls happen.",
    backLabel: "Back to the district",
    backHref: "/shop",
  },
  categoryOptions: [
    { value: "Streetwear", label: "Streetwear" },
    { value: "Luxury", label: "Luxury" },
    { value: "Accessories", label: "Accessories" },
    { value: "Footwear", label: "Footwear" },
  ],
  experienceOptions: [
    { value: "Just starting", label: "Just starting" },
    { value: "Under 1 year", label: "Under 1 year" },
    { value: "1–3 years", label: "1–3 years" },
    { value: "3+ years", label: "3+ years" },
  ],
  theme: {
    acid: "#dfff00",
    pink: "#ff3cac",
    cyan: "#3cf3ff",
    ink: "#08070d",
    backgroundStart: "#0d0917",
    backgroundEnd: "#150714",
    gridOpacity: "0.055",
  },
};

export function normalizeVendorJoinPageContent(content?: Partial<VendorJoinPageContent> | null): VendorJoinPageContent {
  const current = content ?? {};
  return {
    ...defaultVendorJoinPageContent,
    ...current,
    hero: { ...defaultVendorJoinPageContent.hero, ...current.hero, tags: current.hero?.tags ?? defaultVendorJoinPageContent.hero.tags },
    brief: { ...defaultVendorJoinPageContent.brief, ...current.brief, lookingFor: current.brief?.lookingFor ?? defaultVendorJoinPageContent.brief.lookingFor },
    form: { ...defaultVendorJoinPageContent.form, ...current.form, rules: { ...defaultVendorJoinPageContent.form.rules, ...current.form?.rules } },
    status: { ...defaultVendorJoinPageContent.status, ...current.status },
    categoryOptions: current.categoryOptions ?? defaultVendorJoinPageContent.categoryOptions,
    experienceOptions: current.experienceOptions ?? defaultVendorJoinPageContent.experienceOptions,
    theme: { ...defaultVendorJoinPageContent.theme, ...current.theme },
  };
}