import { useEffect, useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { ReturnShippingConversation } from "@/components/returns/ReturnShippingConversation";
const authHeaders = () => ({ Authorization: `Bearer ${localStorage.getItem("token") ?? ""}` });

export default function VendorReturns() {
  const { toast } = useToast();
  const [returns, setReturns] = useState<any[]>([]);
  const load = async () => { const response = await fetch("/api/vendors/returns", { headers: authHeaders() }); if (response.ok) setReturns(await response.json()); };
  useEffect(() => { void load(); }, []);
  const update = async (id: number, status: string, extra = {}) => {
    const response = await fetch(`/api/vendors/returns/${id}`, { method: "PATCH", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ status, ...extra }) });
    const data = await response.json();
    if (!response.ok) toast({ title: "Return not updated", description: data.error, variant: "destructive" }); else { toast({ title: `Return ${status}.` }); await load(); }
  };
  return <div className="space-y-8">
    <header><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Workspace / Returns & Refunds</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight">Returns & Refunds</h1><p className="mt-2 max-w-2xl text-muted-foreground">Review eligible requests, communicate with customers, and inspect returned pieces before they go back into stock.</p></header>
    <div className="grid gap-4 sm:grid-cols-3"><div className="border border-border p-5"><p className="text-[10px] uppercase tracking-widest text-muted-foreground">Needs response</p><p className="mt-2 font-serif text-3xl">{returns.filter(item => item.status === "requested").length}</p></div><div className="border border-border p-5"><p className="text-[10px] uppercase tracking-widest text-muted-foreground">In transit</p><p className="mt-2 font-serif text-3xl">{returns.filter(item => ["approved", "received"].includes(item.status)).length}</p></div><div className="border border-border p-5"><p className="text-[10px] uppercase tracking-widest text-muted-foreground">Inspected</p><p className="mt-2 font-serif text-3xl">{returns.filter(item => item.status === "inspected").length}</p></div></div>
    <section className="space-y-3">{returns.length === 0 ? <div className="border border-dashed border-border p-12 text-center text-sm text-muted-foreground">No return requests yet.</div> : returns.map(item => <article key={item.id} className="border border-border bg-background p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-[10px] uppercase tracking-widest text-muted-foreground">Return #{item.id} · Order #{item.orderId}</p><h2 className="mt-2 font-serif text-xl font-bold capitalize">{item.reason.replaceAll("_", " ")}</h2><p className="mt-1 text-sm text-muted-foreground">{item.description || "No customer note provided."}</p></div><span className="h-fit border border-border px-3 py-1 text-xs font-bold uppercase tracking-widest">{item.status.replaceAll("_", " ")}</span></div><ReturnShippingConversation returnId={item.id} role="vendor" onChange={() => void load()} /><div className="mt-5 flex flex-wrap gap-2">{item.status === "requested" && <><button onClick={() => update(item.id, "approved")} className="bg-foreground px-4 py-2 text-xs font-bold uppercase tracking-widest text-background">Approve after agreement</button><button onClick={() => update(item.id, "rejected")} className="border border-border px-4 py-2 text-xs font-bold uppercase tracking-widest">Reject</button></>}{item.status === "approved" && <button onClick={() => update(item.id, "received")} className="border border-border px-4 py-2 text-xs font-bold uppercase tracking-widest">Mark received</button>}{item.status === "received" && <><button onClick={() => update(item.id, "inspected", { resalable: true })} className="bg-foreground px-4 py-2 text-xs font-bold uppercase tracking-widest text-background">Resalable</button><button onClick={() => update(item.id, "inspected", { resalable: false })} className="border border-border px-4 py-2 text-xs font-bold uppercase tracking-widest">Not resalable</button></>}</div><p className="mt-4 text-xs text-muted-foreground">Response deadline: {new Date(item.responseDeadline).toLocaleString()}</p></article>)}</section>
  </div>;
}